# Generated by Django 5.1.6 on 2025-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
